--- # Initiate OS Reinstallation by copying kernel and initrd and modifying grub.cfg
- synchronize:
    src: "{{boot_dir}}"
    dest: /boot
    set_remote_user: no
  delegate_to: "{{build_server}}"
# hacky:
- shell: "tmp=$(mount -l | grep boot | grep -v efi | cut -d' ' -f 1); echo \"${tmp: -1}\""
  register: part_no
- template:
    src: 49_custom.j2
    dest: /etc/grub.d/49_custom
    mode: "a+x"
- lineinfile:
    insertafter: "EOF"
    line: "GRUB_DEFAULT=reinstall"
    path: "/etc/default/grub"
    state: present
- shell: "grub2-mkconfig > /boot/efi/EFI/fedora/grub.cfg"
