--- # Initiate OS Reinstallation by copying kernel and initrd and modifying grub.cfg
- synchronize:
    src: "{{build_dir}}"
    dest: /boot
    set_remote_user: no
  delegate_to: "{{build_server}}"
# hacky:
#- shell: "tmp=$(mount -l | grep boot | grep -v efi | cut -d' ' -f 1); echo \"${tmp: -1}\""
# New Version that is partition independant
- shell: "tmp=$(df /boot | cut -d' ' -f 1 | tail -n 1); echo \"${tmp: -1}\""
  register: part_no
- shell: "tmp=$(blkid | grep /dev/sda{{part_no.stdout}} | cut -d'=' -f 2 | cut -d' ' -f1); echo $tmp"
  register: uuid
- template:
    src: 49_custom.j2
    dest: /etc/grub.d/49_custom
    mode: "a+x"
- lineinfile:
    insertafter: "EOF"
    line: "GRUB_DEFAULT=reinstall"
    path: "/etc/default/grub"
    state: present
- shell: "grub2-mkconfig > /boot/efi/EFI/fedora/grub.cfg"
  when: efi is defined and efi==1
- shell: "grub2-mkconfig > /boot/grub2/grub.cfg"
  when: efi is undefined or efi!=1

